name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - run: npm ci
      - name: Download Thunderbird
        run: |
          curl -L -o thunderbird.tar.xz "https://download.mozilla.org/?product=thunderbird-latest&os=linux64&lang=en-US"
          tar xJf thunderbird.tar.xz
          mv thunderbird/ thb
      - name: Run tests
        env:
          TB_PATH: thb/thunderbird
        run: npm test
